artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/10VRMp8S2J86Xooj7JTAqOfGnibvetyJX/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_preprocessing:
  root_dir: artifacts/data_preprocessing
  fake_news_path: artifacts/data_ingestion/Fake.csv
  true_news_path: artifacts/data_ingestion/True.csv
  processed_x_train: artifacts/data_preprocessing/X_train_tfidf.pkl
  processed_y_train: artifacts/data_preprocessing/y_train.pkl
  processed_x_test: artifacts/data_preprocessing/X_test_tfidf.pkl
  processed_y_test: artifacts/data_preprocessing/y_test.pkl
  tfidf_vectoriser: artifacts/data_preprocessing/tfidf_vectoriser.pkl

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pkl

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/trained_model.pkl



